package pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="----")
public class QuestionPool {

	@Id
	@Column(name="------")
	private int poolId;
	// primary key
	// autogenerated by DB table
	@Column(name="------")
	private String poolCat;
	@Column(name="------")
	private String poolType;
	@Column(name="------")
	private String poolSubtype;
	@Column(name="------")
	private int noOfQnsInPool;
	
	public int getPoolId() {
		return poolId;
	}
	public void setPoolId(int poolId) {
		this.poolId = poolId;
	}
	public String getPoolCat() {
		return poolCat;
	}
	public void setPoolCat(String poolCat) {
		this.poolCat = poolCat;
	}
	public String getPoolType() {
		return poolType;
	}
	public void setPoolType(String poolType) {
		this.poolType = poolType;
	}
	public String getPoolSubtype() {
		return poolSubtype;
	}
	public void setPoolSubtype(String poolSubtype) {
		this.poolSubtype = poolSubtype;
	}
	public int getNoOfQnsInPool() {
		return noOfQnsInPool;
	}
	public void setNoOfQnsInPool(int noOfQnsInPool) {
		this.noOfQnsInPool = noOfQnsInPool;
	}
	
	
}
