package pojo;

import java.sql.Blob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="----")
public class QuestionBank {
	
	@Id
	@Column(name="------")
	private int qnsId;
	// primary key
	// auto generated by DB table
	@Column(name="------")
	private int poolId;
	// foreign key
	// taken from QuestionPool
	@Column(name="------")
	private Blob qns;
	// contains URL link to uploaded question image
	@Column(name="------")
	private String correctAns;
	
	public int getQnsId() {
		return qnsId;
	}
	public void setQnsId(int qnsId) {
		this.qnsId = qnsId;
	}
	public int getPoolId() {
		return poolId;
	}
	public void setPoolId(int poolId) {
		this.poolId = poolId;
	}
	public Blob getQns() {
		return qns;
	}
	public void setQns(Blob qns) {
		this.qns = qns;
	}
	public String getCorrectAns() {
		return correctAns;
	}
	public void setCorrectAns(String correctAns) {
		this.correctAns = correctAns;
	}
	
	
	
}
