package pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="----")
public class TestDetails {
	
	@Id
	@Column(name="------")
	private int settingsId;
	// primary key
	// auto generated by DB table
	@Column(name="------")
	private int poolId;
	// foregin key
	// taken from QuestionPool
	@Column(name="------")
	private String testCat;
	// taken from QuestionPool
	@Column(name="------")
	private String testType;
	// taken from QuestionPool
	@Column(name="------")
	private String testSubtype;
	// taken from QuestionPool
	@Column(name="------")
	private int noOfQns;
	@Column(name="------")
	private int timeLimit;
	@Column(name="------")
	private Boolean isActive;
	// used to check if test is "deleted" or not
	
	public int getSettingsId() {
		return settingsId;
	}
	public void setSettingsId(int settingsId) {
		this.settingsId = settingsId;
	}
	public int getPoolId() {
		return poolId;
	}
	public void setPoolId(int poolId) {
		this.poolId = poolId;
	}
	public String getTestCat() {
		return testCat;
	}
	public void setTestCat(String testCat) {
		this.testCat = testCat;
	}
	public String getTestType() {
		return testType;
	}
	public void setTestType(String testType) {
		this.testType = testType;
	}
	public String getTestSubtype() {
		return testSubtype;
	}
	public void setTestSubtype(String testSubtype) {
		this.testSubtype = testSubtype;
	}
	public int getNoOfQns() {
		return noOfQns;
	}
	public void setNoOfQns(int noOfQns) {
		this.noOfQns = noOfQns;
	}
	public int getTimeLimit() {
		return timeLimit;
	}
	public void setTimeLimit(int timeLimit) {
		this.timeLimit = timeLimit;
	}
	public Boolean getIsActive() {
		return isActive;
	}
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	
	
	
}
